### ISSUE TITLE
docker 部署后启动报错

### ISSUE THREAD

**Issue by dreamtwi** [kiliokuara/magic-signer-guide#7]
复现步骤：
Centos 7 执行以下指令：
$ docker pull kiliokuara/vivo50:latest
$ docker run -d --restart=always \
  -e SERVER_IDENTITY_KEY=vivo50 \
  -e AUTH_KEY=kfc \
  -e PORT=8888 \
  -p 8888:8888 \
  --log-opt mode=non-blocking --log-opt max-buffer-size=4m \
  -v /home/vivo50/serverData:/app/serverData \
  -v /home/vivo50/testbot:/app/testbot \
  --name vivo50 \
  --memory 200M \
  kiliokuara/vivo50
  
  然后 docker ps 检查容器状态时会发现 vivo50 一直处于 restarting 状态，无限循环。
  以下是 docker logs vivo50 的输出，有错误信息：
2023-07-30 03:38:22 [INFO ] [main] RpcServerBootstrap - unpacking resources.
2023-07-30 03:38:22 [INFO ] [main] n1cbc826620954c6491c6d608dc024736 - extracting linuxfile/ls
Exception in thread "main" java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at kfc.ne6e75658fda8432484ce61cae30527b9.n1cbc826620954c6491c6d608dc024736.a(Unknown Source)
        at tencentlibfekit.vmservice.rpc.RpcServerBootstrap.main(Unknown Source)
Caused by: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base/java.nio.file.Files.copy(Files.java:3161)
        ... 2 more
2023-07-30 03:38:23 [INFO ] [main] RpcServerBootstrap - unpacking resources.
2023-07-30 03:38:23 [INFO ] [main] n1cbc826620954c6491c6d608dc024736 - extracting linuxfile/ls
Exception in thread "main" java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at kfc.ne6e75658fda8432484ce61cae30527b9.n1cbc826620954c6491c6d608dc024736.a(Unknown Source)
        at tencentlibfekit.vmservice.rpc.RpcServerBootstrap.main(Unknown Source)
Caused by: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base/java.nio.file.Files.copy(Files.java:3161)
        ... 2 more
2023-07-30 03:38:24 [INFO ] [main] RpcServerBootstrap - unpacking resources.
2023-07-30 03:38:24 [INFO ] [main] n1cbc826620954c6491c6d608dc024736 - extracting linuxfile/ls
Exception in thread "main" java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at kfc.ne6e75658fda8432484ce61cae30527b9.n1cbc826620954c6491c6d608dc024736.a(Unknown Source)
        at tencentlibfekit.vmservice.rpc.RpcServerBootstrap.main(Unknown Source)
Caused by: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base/java.nio.file.Files.copy(Files.java:3161)
        ... 2 more
2023-07-30 03:38:26 [INFO ] [main] RpcServerBootstrap - unpacking resources.
2023-07-30 03:38:26 [INFO ] [main] n1cbc826620954c6491c6d608dc024736 - extracting linuxfile/ls
Exception in thread "main" java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at kfc.ne6e75658fda8432484ce61cae30527b9.n1cbc826620954c6491c6d608dc024736.a(Unknown Source)
        at tencentlibfekit.vmservice.rpc.RpcServerBootstrap.main(Unknown Source)
Caused by: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base/java.nio.file.Files.copy(Files.java:3161)
        ... 2 more
2023-07-30 03:38:27 [INFO ] [main] RpcServerBootstrap - unpacking resources.
2023-07-30 03:38:27 [INFO ] [main] n1cbc826620954c6491c6d608dc024736 - extracting linuxfile/ls
Exception in thread "main" java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at kfc.ne6e75658fda8432484ce61cae30527b9.n1cbc826620954c6491c6d608dc024736.a(Unknown Source)
        at tencentlibfekit.vmservice.rpc.RpcServerBootstrap.main(Unknown Source)
Caused by: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base/java.nio.file.Files.copy(Files.java:3161)
        ... 2 more
2023-07-30 03:38:30 [INFO ] [main] RpcServerBootstrap - unpacking resources.
2023-07-30 03:38:30 [INFO ] [main] n1cbc826620954c6491c6d608dc024736 - extracting linuxfile/ls
Exception in thread "main" java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at kfc.ne6e75658fda8432484ce61cae30527b9.n1cbc826620954c6491c6d608dc024736.a(Unknown Source)
        at tencentlibfekit.vmservice.rpc.RpcServerBootstrap.main(Unknown Source)
Caused by: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base/java.nio.file.Files.copy(Files.java:3161)
        ... 2 more
2023-07-30 03:38:34 [INFO ] [main] RpcServerBootstrap - unpacking resources.
2023-07-30 03:38:34 [INFO ] [main] n1cbc826620954c6491c6d608dc024736 - extracting linuxfile/ls
Exception in thread "main" java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at kfc.ne6e75658fda8432484ce61cae30527b9.n1cbc826620954c6491c6d608dc024736.a(Unknown Source)
        at tencentlibfekit.vmservice.rpc.RpcServerBootstrap.main(Unknown Source)
Caused by: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base/java.nio.file.Files.copy(Files.java:3161)
        ... 2 more
2023-07-30 03:38:42 [INFO ] [main] RpcServerBootstrap - unpacking resources.
2023-07-30 03:38:42 [INFO ] [main] n1cbc826620954c6491c6d608dc024736 - extracting linuxfile/ls
Exception in thread "main" java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at kfc.ne6e75658fda8432484ce61cae30527b9.n1cbc826620954c6491c6d608dc024736.a(Unknown Source)
        at tencentlibfekit.vmservice.rpc.RpcServerBootstrap.main(Unknown Source)
Caused by: java.nio.file.FileAlreadyExistsException: serverData/resources/linuxfile/ls
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base/java.nio.file.Files.copy(Files.java:3161)
        ... 2 more

**Comment by kiliokuara** [comment]
已更新，尝试最新的镜像
或尝试清理缓存 `serverData`
