### ISSUE TITLE
一段时间后就只能接收消息不能发送消息了

### ISSUE THREAD

**Issue by Lawaxi** [kiliokuara/magic-signer-guide#8]
[KCannot find exception handler from coroutineContext. [m
> 
[KPlease extend SimpleListenerHost.handleException or provide a CoroutineExceptionHandler to the constructor of SimpleListenerHost[m
> 
[K	at net.mamoe.mirai.event.SimpleListenerHost.handleException(JvmMethodListeners.kt:192)[m
> 
[K	at net.mamoe.mirai.event.SimpleListenerHost$special$$inlined$CoroutineExceptionHandler$1.handleException(CoroutineExceptionHandler.kt:111)[m
> 
[K	at net.mamoe.mirai.internal.event.SafeListener.onEvent(SafeListener.kt:75)[m
> 
[K	at net.mamoe.mirai.internal.event.SafeListener$onEvent$1.invokeSuspend(SafeListener.kt)[m
> 
[K	... 9 more[m
> 
[KCaused by: net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler[m
> 
[K	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:147)[m
> 
[K	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:1)[m
> 
[K	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:154)[m
> 
[K	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)[m
> 
[K	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)[m
> 
[K	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)[m
> 
[K	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)[m
> 
[K	... 4 more[m
> 
[KCaused by: java.lang.reflect.InvocationTargetException[m
> 
[K	at jdk.internal.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)[m
> 
[K	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[m
> 
[K	at java.base/java.lang.reflect.Method.invoke(Method.java:566)[m
> 
[K	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:140)[m
> 
[K	... 10 more[m
> 
[KCaused by: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:9999[m
> 
[K	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)[m
> 
[K	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:201)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar//xyz.cssxsh.mirai.tool.ViVo50$Session.check(ViVo50.kt:326)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar//xyz.cssxsh.mirai.tool.ViVo50$Session.websocket(ViVo50.kt:368)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar//xyz.cssxsh.mirai.tool.ViVo50$Session.sendPacket(ViVo50.kt:380)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar//xyz.cssxsh.mirai.tool.ViVo50$Session.sendCommand(ViVo50.kt:393)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar//xyz.cssxsh.mirai.tool.ViVo50.qSecurityGetSign(ViVo50.kt:207)[m
> 
[K	at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt.buildRawUniPacket(OutgoingPacket.kt:139)[m
> 
[K	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbSendMsg.createToGroupImpl$mirai_core(MessageSvc.PbSendMsg.kt:744)[m
> 
[K	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvc_PbSendMsgKt.createToGroup(MessageSvc.PbSendMsg.kt:585)[m
> 
[K	at net.mamoe.mirai.internal.message.protocol.outgoing.GroupMessageProtocolStrategy.createPacketsForGeneralMessage$suspendImpl(MessageProtocolStrategy.kt:150)[m
> 
[K	at net.mamoe.mirai.internal.message.protocol.outgoing.GroupMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt)[m
> 
[K	at net.mamoe.mirai.internal.message.protocol.outgoing.GroupMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt:139)[m
> 
[K	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.process(GeneralMessageSenderProtocol.kt:66)[m
> 
[K	at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:26)[m
> 
[K	at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:20)[m
> 
[K	at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:287)[m
> 
[K	at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process(ProcessorPipeline.kt)[m
> 
[K	at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoingImpl(MessageProtocolFacade.kt:361)[m
> 
[K	at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoing(MessageProtocolFacade.kt:345)[m
> 
[K	at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.preprocessAndSendOutgoing(MessageProtocolFacade.kt)[m
> 
[K	at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:263)[m
> 
[K	at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage$suspendImpl(GroupImpl.kt:221)[m
> 
[K	at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage(GroupImpl.kt)[m
> 
[K	at net.mamoe.mirai.contact.Group.sendMessage$suspendImpl(Group.kt:208)[m
> 
[K	at net.mamoe.mirai.contact.Group.sendMessage(Group.kt)[m
> 
[K	at net.mamoe.mirai.contact.Group$sendMessage$3.invoke(Group.kt)[m
> 
[K	at net.mamoe.mirai.contact.Group$sendMessage$3.invoke(Group.kt)[m
> 
[K	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)[m
> 
[K	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)[m
> 
[K	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)[m
> 
[K	at me.him188.kotlin.jvm.blocking.bridge.internal.RunSuspendKt.$runSuspend$(RunSuspend.kt:18)[m
> 
[K	at net.mamoe.mirai.contact.Group.sendMessage(Group.kt)[m
> 
[K	at shitboy-0.1.10-test6.mirai2.jar//net.lawaxi.ListenerYLG.sendXenonRecallMessage(ListenerYLG.java:112)[m
> 
[K	at shitboy-0.1.10-test6.mirai2.jar//net.lawaxi.ListenerYLG.onGroupRecall(ListenerYLG.java:90)[m
> 
[K	... 14 more[m
> 
[KCaused by: java.net.ConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:9999[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)[m
> 
[K	at java.base/java.lang.Thread.run(Thread.java:829)[m
> 
[KCaused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:9999[m
> 
[KCaused by: java.net.ConnectException: Connection refused[m
> 
[K	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)[m
> 
[K	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)[m
> 
[K	at fix-protocol-version-1.9.5.mirai2.jar[private]//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)[m
> 
[K	at java.base/java.lang.Thread.run(Thread.java:829)[m
> 
[K[0m[m

**Comment by Lawaxi** [comment]
重启：
[91m2023-07-31 19:05:04 E/Bot.198344963: java.lang.RuntimeException: 请检查 magic-signer-guide by http://localhost:9999 的可用性[m
java.lang.RuntimeException: 请检查 magic-signer-guide by http://localhost:9999 的可用性[m
	at fix-protocol-version-1.9.5.mirai2.jar//xyz.cssxsh.mirai.tool.KFCFactory.createForBot(KFCFactory.kt:97)[m
	at net.mamoe.mirai.internal.network.components.EncryptServiceHolderImpl.<init>(EncryptServiceHolder.kt:49)[m
	at net.mamoe.mirai.internal.QQAndroidBot.createBotLevelComponents(QQAndroidBot.kt:288)[m
	at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:192)[m
	at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:191)[m
	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:47)[m
	at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:191)[m
	at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:300)[m
	at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:312)[m
	at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:305)[m
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:277)[m
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:249)[m
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)[m
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:51)[m
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:54)[m
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:53)[m
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)[m
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getScope(SelectorNetworkHandler.kt:53)[m
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:112)[m
	at net.mamoe.mirai.internal.AbstractBot$coroutineContext$1$1.invoke(AbstractBot.kt:65)[m
	at net.mamoe.mirai.internal.AbstractBot$coroutineContext$1$1.invoke(AbstractBot.kt:59)[m
	at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1392)[m
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1520)[m
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)[m
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)[m
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)[m
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)[m
	at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:696)[m
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:667)[m
	at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:632)[m
	at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:617)[m
	at kotlinx.coroutines.Job$DefaultImpls.cancel$default(Job.kt:183)[m
	at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:122)[m
	at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:98)[m
	at net.mamoe.mirai.Bot.close(Bot.kt:188)[m
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge$doStart$11$1.invokeSuspend(MiraiConsoleImplementationBridge.kt:433)[m
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)[m
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)[m
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)[m
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)[m
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)[m
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)[m
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)[m
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)[m
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:369)[m
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)[m
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)[m
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)[m
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)[m
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[m
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[m
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[m
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)[m
	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)[m
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)[m
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)[m
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)[m
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)[m
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)[m
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)[m
	at org.itxtech.mcl.Loader.start(Loader.java:196)[m
	at org.itxtech.mcl.Loader.main(Loader.java:84)[m
Caused by: java.net.ConnectException: Connection refused (Connection refused)[m
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)[m
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)[m
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)[m
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)[m
	at java.base/java.net.Socket.connect(Socket.java:609)[m
	at java.base/java.net.Socket.connect(Socket.java:558)[m
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)[m
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:507)[m
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:602)[m
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:275)[m
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:374)[m
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:395)[m
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)[m
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)[m
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)[m
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)[m
	at fix-protocol-version-1.9.5.mirai2.jar//xyz.cssxsh.mirai.tool.KFCFactory.createForBot(KFCFactory.kt:95)[m
	... 61 more[m

**Comment by kiliokuara** [comment]
docker logs vivo50

**Comment by Lawaxi** [comment]
忘了看了 等下次吧 :)
重启能熬两三天
