### ISSUE TITLE
docker部署内存占用异常

### ISSUE THREAD

**Issue by hui-ld** [kiliokuara/magic-signer-guide#9]
运行环境Debian11.1

日志
```
2023-07-31 15:36:57 [INFO ] [main] RpcServerBootstrap - unpacking resources.
2023-07-31 15:36:57 [INFO ] [main] RpcServerBootstrap - downloading mobile qq apk
2023-07-31 15:36:57 [INFO ] [main] n9e30d450041548ce8a3c88502172b430 - checking sha1 of apk serverData/android-8.9.58.apk
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.nio.file.Files.read(Files.java:3239)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3296)
	at kfc.n55600a3e0bd040beb5650998c3f54f46.n9e30d450041548ce8a3c88502172b430.c(Unknown Source)
	at kfc.n55600a3e0bd040beb5650998c3f54f46.n9e30d450041548ce8a3c88502172b430.b(Unknown Source)
	at tencentlibfekit.vmservice.rpc.RpcServerBootstrap.main(Unknown Source)
2023-07-31 15:36:57 [INFO ] [main] RpcServerBootstrap - unpacking resources.
2023-07-31 15:36:57 [INFO ] [main] RpcServerBootstrap - downloading mobile qq apk
2023-07-31 15:36:57 [INFO ] [main] n9e30d450041548ce8a3c88502172b430 - checking sha1 of apk serverData/android-8.9.58.apk
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.nio.file.Files.read(Files.java:3239)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3296)
	at kfc.n55600a3e0bd040beb5650998c3f54f46.n9e30d450041548ce8a3c88502172b430.c(Unknown Source)
	at kfc.n55600a3e0bd040beb5650998c3f54f46.n9e30d450041548ce8a3c88502172b430.b(Unknown Source)
	at tencentlibfekit.vmservice.rpc.RpcServerBootstrap.main(Unknown Source)
```
把  --memory 200M 这一行去掉可以正常运行，但内存占用多了好多，小水管服务器撑不住

**Comment by kiliokuara** [comment]
updated, 尝试拉取最新镜像
